
spring:

 datasource:
  driverClassName: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3306/libaryproject
  username: root
  password: 1234


 thymeleaf:
   prefix: classpath:/templates/
   suffix: .html

 jpa:
   properties: # property 사용 설정
     hibernate: # hibernate property 설정
       format_sql: true
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   open-in-view: false
   show-sql: true
   hibernate:
     format_sql: true
     ddl-auto: update
 logging:
   level:
     # hibernate 가 남기는 모든 로그가 debug모드로 설정
     # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
     org.hibernate.SQL: debug
     org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정